import { DetectedCategory, SmartBackgroundPreset } from "@/types/schema";

export const CATEGORY_BACKGROUND_PRESETS: Record<DetectedCategory | "all", SmartBackgroundPreset[]> = {
  person: [
    {
      id: "person-office",
      name: "Office",
      category: "person",
      type: "gradient",
      value: "linear-gradient(135deg, #0F172A 0%, #1E293B 50%, #334155 100%)",
      previewBg: "bg-gradient-to-br from-slate-900 to-slate-700",
      description: "Modern executive office aesthetic with subtle depth",
    },
    {
      id: "person-studio",
      name: "Studio",
      category: "person",
      type: "gradient",
      value: "radial-gradient(circle at 50% 30%, #FFFFFF 0%, #E2E8F0 60%, #CBD5E1 100%)",
      previewBg: "bg-gradient-to-br from-white to-slate-200",
      description: "High-key studio portrait radial lighting",
    },
    {
      id: "person-outdoor",
      name: "Outdoor",
      category: "person",
      type: "gradient",
      value: "linear-gradient(135deg, #2D1B00 0%, #78350F 40%, #B45309 80%, #D97706 100%)",
      previewBg: "bg-gradient-to-br from-amber-950 to-amber-600",
      description: "Warm golden hour natural outdoor ambient glow",
    },
    {
      id: "person-linkedin",
      name: "LinkedIn",
      category: "person",
      type: "gradient",
      value: "linear-gradient(135deg, #002244 0%, #004182 50%, #0A66C2 100%)",
      previewBg: "bg-gradient-to-br from-blue-950 to-sky-600",
      description: "Corporate LinkedIn authority blue backdrop",
    },
  ],
  product: [
    {
      id: "product-white-studio",
      name: "White Studio",
      category: "product",
      type: "gradient",
      value: "radial-gradient(circle at 50% 35%, #FFFFFF 0%, #F1F5F9 70%, #E2E8F0 100%)",
      previewBg: "bg-gradient-to-br from-white to-slate-200",
      description: "Amazon & Shopify pure white studio showcase",
    },
    {
      id: "product-gradient",
      name: "Gradient",
      category: "product",
      type: "gradient",
      value: "linear-gradient(135deg, #090B1E 0%, #1E1B4B 50%, #4F46E5 100%)",
      previewBg: "bg-gradient-to-br from-indigo-950 to-indigo-600",
      description: "Vibrant modern neon e-commerce hero gradient",
    },
    {
      id: "product-ecommerce",
      name: "E-commerce",
      category: "product",
      type: "gradient",
      value: "linear-gradient(180deg, #1E293B 0%, #0F172A 100%)",
      previewBg: "bg-gradient-to-b from-slate-800 to-slate-950",
      description: "Neutral dark platform with subtle floor contrast",
    },
  ],
  pet: [
    {
      id: "pet-nature",
      name: "Nature",
      category: "pet",
      type: "gradient",
      value: "linear-gradient(135deg, #022C22 0%, #065F46 50%, #10B981 100%)",
      previewBg: "bg-gradient-to-br from-emerald-950 to-emerald-500",
      description: "Lush botanical meadow green scenery",
    },
    {
      id: "pet-park",
      name: "Park",
      category: "pet",
      type: "gradient",
      value: "linear-gradient(135deg, #14532D 0%, #4D7C0F 50%, #84CC16 100%)",
      previewBg: "bg-gradient-to-br from-green-900 to-lime-500",
      description: "Sunlit outdoor grassy park backdrop",
    },
    {
      id: "pet-home",
      name: "Home",
      category: "pet",
      type: "gradient",
      value: "linear-gradient(135deg, #3E2723 0%, #5D4037 50%, #8D6E63 100%)",
      previewBg: "bg-gradient-to-br from-warm-gray-900 to-amber-700",
      description: "Warm cozy living room interior vibe",
    },
  ],
  vehicle: [
    {
      id: "vehicle-road",
      name: "Road",
      category: "vehicle",
      type: "gradient",
      value: "linear-gradient(180deg, #020617 0%, #0F172A 50%, #1E293B 100%)",
      previewBg: "bg-gradient-to-b from-slate-950 to-slate-800",
      description: "High-contrast midnight asphalt highway",
    },
    {
      id: "vehicle-showroom",
      name: "Showroom",
      category: "vehicle",
      type: "gradient",
      value: "radial-gradient(circle at 50% 20%, #334155 0%, #090D16 100%)",
      previewBg: "bg-gradient-to-br from-slate-700 to-slate-950",
      description: "Luxury automotive showroom spotlight stage",
    },
    {
      id: "vehicle-garage",
      name: "Garage",
      category: "vehicle",
      type: "gradient",
      value: "linear-gradient(135deg, #18181B 0%, #27272A 50%, #3F3F46 100%)",
      previewBg: "bg-gradient-to-br from-zinc-900 to-zinc-700",
      description: "Industrial brushed metallic garage aesthetic",
    },
  ],
  food: [
    {
      id: "food-gourmet",
      name: "Gourmet",
      category: "food",
      type: "gradient",
      value: "radial-gradient(circle at 50% 35%, #2D1B00 0%, #1A0F00 60%, #080400 100%)",
      previewBg: "bg-gradient-to-br from-amber-950 to-stone-950",
      description: "Warm artisanal restaurant table ambient spotlight",
    },
    {
      id: "food-fresh",
      name: "Fresh Botanical",
      category: "food",
      type: "gradient",
      value: "linear-gradient(135deg, #022C22 0%, #064E3B 50%, #047857 100%)",
      previewBg: "bg-gradient-to-br from-emerald-950 to-emerald-600",
      description: "Lush farm-to-table organic green backdrop",
    },
    {
      id: "food-marble",
      name: "Kitchen Studio",
      category: "food",
      type: "gradient",
      value: "radial-gradient(circle at 50% 30%, #FFFFFF 0%, #F1F5F9 60%, #CBD5E1 100%)",
      previewBg: "bg-gradient-to-br from-white to-slate-200",
      description: "Bright modern culinary kitchen showcase",
    },
  ],
  document: [
    {
      id: "document-clean",
      name: "Clean Slate",
      category: "document",
      type: "gradient",
      value: "radial-gradient(circle at 50% 30%, #FFFFFF 0%, #E2E8F0 100%)",
      previewBg: "bg-gradient-to-br from-white to-slate-200",
      description: "High-contrast document archive scanning stage",
    },
    {
      id: "document-desk",
      name: "Executive Desk",
      category: "document",
      type: "gradient",
      value: "linear-gradient(135deg, #0F172A 0%, #1E293B 60%, #334155 100%)",
      previewBg: "bg-gradient-to-br from-slate-900 to-slate-700",
      description: "Professional corporate desk backdrop",
    },
  ],
  logo: [
    {
      id: "logo-dark",
      name: "Obsidian",
      category: "logo",
      type: "gradient",
      value: "radial-gradient(circle at 50% 30%, #131A3A 0%, #0A0B1E 70%, #05060F 100%)",
      previewBg: "bg-gradient-to-br from-slate-900 to-[#05060F]",
      description: "High-contrast brand mark dark showcase",
    },
    {
      id: "logo-neon",
      name: "Cyber Neon",
      category: "logo",
      type: "gradient",
      value: "linear-gradient(135deg, #090B1E 0%, #1E1B4B 50%, #4F46E5 100%)",
      previewBg: "bg-gradient-to-br from-indigo-950 to-indigo-600",
      description: "Vibrant modern brand identity glow",
    },
    {
      id: "logo-white",
      name: "Pure White",
      category: "logo",
      type: "gradient",
      value: "radial-gradient(circle at 50% 35%, #FFFFFF 0%, #F8FAFC 100%)",
      previewBg: "bg-white",
      description: "App store & icon clean presentation",
    },
  ],
  screenshot: [
    {
      id: "screenshot-dark",
      name: "Tech Slate",
      category: "screenshot",
      type: "gradient",
      value: "linear-gradient(180deg, #0A0B1E 0%, #131A3A 100%)",
      previewBg: "bg-gradient-to-b from-[#0A0B1E] to-[#131A3A]",
      description: "Modern developer UI showcase backdrop",
    },
    {
      id: "screenshot-indigo",
      name: "Indigo Glass",
      category: "screenshot",
      type: "gradient",
      value: "linear-gradient(135deg, #0F172A 0%, #1E1B4B 50%, #312E81 100%)",
      previewBg: "bg-gradient-to-br from-slate-900 to-indigo-900",
      description: "Futuristic software presentation aesthetic",
    },
  ],
  illustration: [
    {
      id: "illustration-synthwave",
      name: "Synthwave",
      category: "illustration",
      type: "gradient",
      value: "linear-gradient(135deg, #1E1B4B 0%, #581C87 50%, #BE185D 100%)",
      previewBg: "bg-gradient-to-br from-purple-950 to-pink-600",
      description: "Vibrant creative pop-art gradient",
    },
    {
      id: "illustration-pastel",
      name: "Pastel Studio",
      category: "illustration",
      type: "gradient",
      value: "radial-gradient(circle at 50% 30%, #FFFFFF 0%, #F3E8FF 60%, #E9D5FF 100%)",
      previewBg: "bg-gradient-to-br from-white to-purple-200",
      description: "Soft studio lighting for characters and stickers",
    },
    {
      id: "illustration-dark",
      name: "Midnight Art",
      category: "illustration",
      type: "gradient",
      value: "linear-gradient(135deg, #020617 0%, #0A0B1E 60%, #131A3A 100%)",
      previewBg: "bg-gradient-to-br from-slate-950 to-[#131A3A]",
      description: "Dramatic dark gallery canvas",
    },
  ],
  other: [
    {
      id: "other-studio",
      name: "Studio Clean",
      category: "other",
      type: "gradient",
      value: "radial-gradient(circle at 50% 35%, #FFFFFF 0%, #E2E8F0 100%)",
      previewBg: "bg-gradient-to-br from-white to-slate-200",
      description: "Clean neutral high-key radial lighting",
    },
    {
      id: "other-neon",
      name: "Neon Indigo",
      category: "other",
      type: "gradient",
      value: "linear-gradient(135deg, #0F172A 0%, #1E1B4B 50%, #312E81 100%)",
      previewBg: "bg-gradient-to-br from-blue-900 to-indigo-950",
      description: "Modern cyberpunk glow aesthetic",
    },
    {
      id: "other-dark",
      name: "Obsidian Dark",
      category: "other",
      type: "gradient",
      value: "linear-gradient(135deg, #020617 0%, #0A0B1E 60%, #131A3A 100%)",
      previewBg: "bg-gradient-to-br from-slate-950 to-[#131A3A]",
      description: "Sleek dark minimalist backdrop",
    },
  ],
  all: [
    {
      id: "transparent",
      name: "Transparent",
      category: "all",
      type: "pattern",
      value: "transparent",
      previewBg: "checkerboard-pattern",
      description: "Pure lossless alpha transparent canvas",
    },
  ],
};

export const TRANSPARENT_PRESET: SmartBackgroundPreset = {
  id: "transparent",
  name: "Transparent",
  category: "all",
  type: "pattern",
  value: "transparent",
  previewBg: "checkerboard-pattern",
  description: "Pure lossless alpha transparent canvas",
};

export function getRecommendedPresets(category?: DetectedCategory | null): SmartBackgroundPreset[] {
  const cat = category || "other";
  const catPresets = CATEGORY_BACKGROUND_PRESETS[cat] || CATEGORY_BACKGROUND_PRESETS.other;
  return [TRANSPARENT_PRESET, ...catPresets];
}
